### ISSUE TITLE
Run Gazebo simulation for 5 robots as the physical scenario.

### ISSUE THREAD

**Issue by 2000222** [hanzheteng/pioneer_mrs#2]
I just run "roslaunch pioneer_mrs multi-robot.launch pose:=gazebo machine:=gazebo" to get results as in the physical scenario, but I get the log information as follows: 

... logging to /home/ubuntu/.ros/log/e1cfbaaa-98f9-11eb-8e1a-04d4c4ad1764/roslaunch-ubuntu-20691.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

RLException: cannot resolve host address for machine [hzteng]
The traceback for the exception was written to the log file.

So how can I solve this problem in Gazebo? 
Thank u very much.

**Comment by hanzheteng** [comment]
In `config/robots.machine` file and `config/env.bash` file, please replace `hzteng` with the hostname of your local machine (or `localhost` if you plan to run simulation only), and replace `thz_ws` with the actual folder name of the ROS workspace.

In details, `robots.machine` file is included in `multi-robots.launch` to load hostname for each machine. The hostname will then be resolved by `/etc/hosts` file to obtain the IP address of each machine in the network. `hzteng` was the hostname I used before in development and does not exist in your `/etc/hosts` file, so the error `RLException: cannot resolve host address for machine [hzteng]` comes. 

In order to get this package run successfully, there are multiple places to change (hostname, workspace folder, ROS kinetic/melodic, etc.)

**Comment by 2000222** [comment]
Thanks a lot, my problem has been solved.
